### ISSUE TITLE
Screenshot blank

### ISSUE THREAD

**Issue by SebastianHD** [HgAlexx/Hg.SaveHistory#1]
Getting black screen shots on a multi screen setup. Seems to be the correct size for what I'm running doom eternal at (720p on 1080p screen). Don't see anything though, including desktop.

**Comment by SebastianHD** [comment]
Just saw the comments on having to use openGL or windowed

**Comment by HgAlexx** [comment]
Taking screenshot of Wulkan may have evolve since the last time I check, I'll see if this can be improved now.
