### ISSUE TITLE
Screenshot quality cannot be changed

### ISSUE THREAD

**Issue by SebastianHD** [HgAlexx/Hg.SaveHistory#2]
Selecting screenshot quality always returns to high (png). 

Not sure why each quality uses different format (jpeg, gif, png) instead of sticking with a single format and changing the quality by using compression and resolution scaling.

**Comment by HgAlexx** [comment]
It is indeed a format settings but I wanted to emphasize the quality aspect of it (png is better than jpg which is better than gif).
Playing with compression and scaling a little bit overkill for this feature ;)

However the menu is not plugged properly, it will be fixed asap.

**Comment by SebastianHD** [comment]
I get it; it's not important in this application.

Just as a side note, these formats have completely different intended applications,; the image size is just a consequence of the features. For the purpose of having a reference image to identify the correct save, I would argue that jpg is the correct choice. But maybe that is a lack of imagination on my part as to what the purpose could be for.

**Comment by HgAlexx** [comment]
Correct. It is very easy to provide choice between these 3 formats with a trade off between quality and size.
For people who care about the quality, they can pick PNG, if they don't then JPG, and if backup size is an issue then GIF.

Thanks for the report and feedback!
