### ISSUE TITLE
doom eternal loading

### ISSUE THREAD

**Issue by SebastianHD** [HgAlexx/Hg.SaveHistory#3]
I know doom eternal corrupts its save files when overwriting the file while the game is running. However, the utility of this SW is not as useful as I had hoped without this feature. Is there no way to restore a save while the game is running, at least while on the main menu screen?

**Comment by HgAlexx** [comment]
Unfortunately no, DE do not reload the state of saves while entering the save menu (from main screen) like D16 does.
There is nothing I can do about that :(

**Comment by SebastianHD** [comment]
Do you think there could be some mod that integrates with this? I have this vague recollection that I have seen something like that, but I didn't find anything in my initial search.

**Comment by HgAlexx** [comment]
I have no idea, you should ask the modding community, maybe something can be done.
