### ISSUE TITLE
[Features Request] Start with Windows, Minimize on startup, Minimize to tray, Start auto-backup after opening a profile

### ISSUE THREAD

**Issue by LeoTN** [HgAlexx/Hg.SaveHistory#5]
**Is your feature request related to a problem?**
>It would be great if the application could launch in the background, when I start playing e.g. Satisfactory. Maybe I didn't find the option to do that, but for now I always have to keep the application open and always toggle the Auto Backup Button once to work while playing. Is there a better alternative or a setting I haven't done?

**Describe the solution you'd like.**
>Maybe add an option that either allows the application to be launched when the computer boots up and it stays in the background until a supported game is played or the software detects the launch and runs itself to back up the game saves automatically.

**Thanks you for this great piece of software :)**

**Comment by HgAlexx** [comment]
Hello,

Here what I could do:
1. Add an option to start the application with Windows
2. Add an option to minimize the application to tray instead of taskbar
3. Add an option to open last used profile on startup (application settings)
4. Add an option to start auto-back on startup (per profile settings)

Note that you can already do 1. by copying a shortcut to the application in your startup folder, usually:
`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`


I might be able to work on those around christmas.

**Comment by LeoTN** [comment]
Yeah, I currently use a scheduled task which starts the app with a cmd window like this: "start "" /min PATH_TO_APPLICATION". The downside is that the window still exists in the task bar, but that isn't too bad. 
The last two points would be more important to me so that you don't have to toggle the backup manually. 
You could also make the program accept parameters at launch e.g. with the command line, to set the profile to be loaded or the state of the AutoBackup button (in case that the state is not saved in the profile already) :)

**Comment by HgAlexx** [comment]
I've finish to implement all 4 new features.

I need to do some more tests, but a new release should be ready in a few days.

**Comment by HgAlexx** [comment]
Regarding opening a specific profile via the command line, I'll have a look after the next release.

**Comment by LeoTN** [comment]
> I've finish to implement all 4 new features.
> 
> I need to do some more tests, but a new release should be ready in a few days.

Nice to hear, I can also assist you with testing if you want.

**Comment by HgAlexx** [comment]
Done.

https://github.com/HgAlexx/Hg.SaveHistory/releases/tag/v0.9.0

**Comment by LeoTN** [comment]
The feature works fine. Thanks for the addition :D
